### DISCUSSION TITLE
No messages received on WhatsApp

### DISCUSSION THREAD

**Discussion by abhijitjaiswal** [hyperjumptech/monika#1049] [General]
Hi, I didn't receive any message on WhatsApp the I tried registering my mobile number here: when signed up at https://whatsapp.hyperjump.tech/?tab=register 
Can somebody help here ?

**Comment by sapiderman** [comment]
It might be a connection issue, we'll check it out.

**Reply by abhijitjaiswal** [reply]
Thanks for quick reply. Hope it will get solved in some time.

**Reply by abhijitjaiswal** [reply]
Still waiting on it to test out WhatsApp integration…

**Reply by sapiderman** [reply]
Hi @abhijitjaiswal,

A little update. We seem to have sort out everything.

In Monika have you setup properly for the whatsaap notifier? You would need to have something like this in your YAML config file:

```yaml
notifications:
  - id: my-unique-monika-notif-id
    type: monika-notif
    data:
      url: https://whatsapp.hyperjump.tech/api/notify?token=your_token_here 
```

where do you get your token? You can sign up here: https://whatsapp.hyperjump.tech/?tab=register
An https link and your token will be sent to your whatsapp number, which you can use.
