### DISCUSSION TITLE
Gmail notification issue

### DISCUSSION THREAD

**Discussion by arshadmech** [hyperjumptech/monika#1196] [Q&A]
Hi there,

This is Arshad.

When i am doing configuration for url, i added gmail notification alert. When i am running the monika, i am getting this error. please find the yaml file below and error.
<img width="454" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/6bb033c4-e880-4fa1-a2c2-781e4515500e">
notifications:
  - id: test
    type: smtp
    data:
      recipients: ["arshad@gmail.com","arshadmaksj@gmail.com"]
      hostname: smtp.gmail.com
      port: 587
      username: ovalteste@gmail.com
      password: password@123
probes:
  - id: '1'
    name: Monika Landing Page
    description: Landing page of awesome Monika
    interval: 10 # in seconds
    requests:
      - url: https://engineering.net/performance
        timeout: 7000 # in milliseconds
    alerts: []
    
    Do i need to add anything more????

**Comment by arshadmech** [comment]
Hi @sapiderman 
any update??

**Comment by sapiderman** [comment]
Hi @arshadmech, Thanks for the report, !'ll look into it.

**Comment by sapiderman** [comment]
hi @arshadmech 

Gmail worked for me with no issues. Do you have quotation mark (') around your email and password (just in case)?
Also i've used an "app password" for monika to use and not my gmail password. See if that works for you.

![image](https://github.com/hyperjumptech/monika/assets/964106/af9aa5a7-58df-4e02-8cff-73e86d1584df)

  
For your reference, [about app password](https://support.google.com/accounts/answer/185833?visit_id=638333833978379519-3467947102&p=InvalidSecondFactor&rd=1).

**Comment by arshadmech** [comment]
Hi @sapiderman ,

Thanks for the update...
i am also using gmail app password as a password, but not sure why i am getting error.?
still encounter with the same error.

**Comment by sapiderman** [comment]
Hi @arshadmech,

Have you had any progress using the gmail smtp? Did you get it to work?

**Comment by arshadmech** [comment]
Hi @sapiderman ,

I am still getting same error, so i stopped working on it. Can you please send me a sample yaml file for the gmail notification.
i am not sure what i am missing.

**Comment by sapiderman** [comment]
Sure, I'm using plain vanilla config something like this:

```yaml
  - id: smtp-maitrap
    type: smtp
    data:
      recipients: ['test@example.com']
      hostname: smtp.mailtrap.io
      port: 2525
      username: 'username123'
      password: 'password123'

  - id: smtp-google
    type: smtp
    data:
      recipients: ['everyone@mail.earth']
      hostname: smtp.gmail.com
      port: 587
      username: 'just.me@example.com'
      password: '123 123 123 123'
```

As a check, maybe try mailtrap.io, or some other similar service just to see if you can get through. The above settings works for me. Hope this helps.

**Comment by sapiderman** [comment]
Sure, I'm using plain vanilla config something like this:

```yaml
  - id: smtp-maitrap
    type: smtp
    data:
      recipients: ['test@example.com']
      hostname: smtp.mailtrap.io
      port: 2525
      username: 'username123'
      password: 'password123'

  - id: smtp-google
    type: smtp
    data:
      recipients: ['everyone@mail.earth']
      hostname: smtp.gmail.com
      port: 587
      username: 'just.me@example.com'
      password: '123 123 123 123'
```

As a check, maybe try mailtrap.io, or some other similar email just to see if you can get through. The above settings works for me. Hope this helps.

**Comment by arshadmech** [comment]
Hi @sapiderman ,

still i am getting same error. please find my yaml file screenshot below and let me know if i need to add anything.
<img width="187" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/b3eac3f9-6f91-41d3-a748-b8ee1be05134">

<img width="458" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/0773f4d4-3d84-4734-aee3-e2574f80a079">

**Comment by shivachintu123** [comment]
Hi @sapiderman 
I'm configuring email notifications using the Monika alerting tool. While executing the YAML file, I encountered an error. Could you please take a look at my YAML and let me know if I missed anything?"


Monika.yaml 

![monika-yaml file](https://github.com/hyperjumptech/monika/assets/59116970/a89417b7-30bd-4fcd-b2f3-b4557db09e38)

Error meassage:
<img width="1260" alt="Monika-error" src="https://github.com/hyperjumptech/monika/assets/59116970/34cade03-42e9-4054-813c-be4f272f75bb">

**Comment by arshadmech** [comment]
Hi @sapiderman and TEAM,

any update on this,
<img width="713" alt="image" src="https://github.com/hyperjumptech/monika/assets/77534698/7ee6927a-8be1-4577-8b6c-e8ef0609be03">

**Comment by sapiderman** [comment]
hi @arshadmech, i tried using your credentials getting username and password wrong error: can you check name and password?

```yaml
  - id: test
    type: smtp
    data:
      recipients: ['some.address@me.com']
      hostname: smtp.gmail.com
      port: 587
      username: oval345@gmail.com
      password: ypvghnncbfvhxsir  
```
