### DISCUSSION TITLE
Only "1" appears in localhost:3001/metrics > monika_probe_result.

### DISCUSSION THREAD

**Discussion by Sanitater941** [hyperjumptech/monika#1326] [Q&A] [answered]
Creating an API monitoring system using monika.

The API failed intentionally, but on http://localhost:3001/metrics,
The "monika_probe_result" data is not updated, and the past successful history of "1" continues to be exposed.

If it fails, what can I do to get "0" exposed?

---

here is my monika.yml:
(this http request was Failed)
```yml
probes:
   - id: '4'
     name: name
     interval: 60 # in seconds
     requests:
      - method: PATCH
        url: {url}
        timeout: 7000 # in milliseconds
        saveBody: true
        headers:
           Authorization: {Authorization}
           Content-Type: application/json
        body: 
           name : name
        followRedirects: 1
     incidentThreshold: 3
     alerts: 
      - assertions: response.status != 204
        message: Status not 204 
```
<img width="1251" alt="화면 캡처 2024-12-04 162404" src="https://github.com/user-attachments/assets/e283c6ec-4632-4d24-ae1c-5de7cc1d067f">

**Comment by Sanitater941** [comment]
hi @sapiderman 
is there any update?

**Reply by sapiderman** [reply]
hi @Sanitater941 

I have a question, how many iterations have you let the probe run in your example above? What is the result if you let it run 10 times? Have you tried the --verbose switch to see the logs internally in more detail?

Let me know how it goes.

**Reply by Sanitater941** [reply]
hi @sapiderman 

Yes, based on "id4", If it fails more than 10 times, it is exposed to alert_counter.
but not to monika_probe_result and monika_request_status_code_info.

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/7a142cb3-5dc9-43ab-80ac-ddbd8e63aa91">

**Comment by sapiderman** [comment]
@Sanitater941 thanks for the additional info. Looking into it now.

**Comment by sapiderman** [comment]
@Sanitater941 

I've finally got round to trying it out, so far everything checks out.  What is the http response or status code from your PATCH to your url/API? Does the PATCH request fail immediately? a 401 or 404? Did you get the "status not 204" alert? 

I'm using this setup (similar to yours). 

```yaml
probes:
  - id: 'http-1'
    name: 'status-401-test'
    requests:
      - url: https://httpbin.org/status/401
        method: PATCH
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
      - assertion: response.ime > 2000
        message: Too sloow
```  

Here's my localhost:3001/metrics



![image](https://github.com/user-attachments/assets/cc1dcf1d-d88e-4325-8cc5-249dd421c50a)


Are you able to get the same result the above config yaml?
