### DISCUSSION TITLE
[Question] Is it possible for Monika Config Yaml to read some values ​​from Environment Variables?

### DISCUSSION THREAD

**Discussion by gihif** [hyperjumptech/monika#1339] [Q&A]
Hi everyone, I am a new user at Monika, and currently I am exploring Monika as our observability tool to do synthetic monitoring.

I would like to ask about Monika's capability to read configuration values ​​taken from EnvVar.
Let's take an example, suppose I have a Monika Configuration Yaml as follows.
```
probes:
  - id: '1'
    name: 'Example: get Time'
    description: Probe
    interval: 10 # in seconds
    requests:
      - method: POST
        url: https://mybackend.org/user/login
        timeout: 7000 # in milliseconds
        saveBody: true
        headers:
          Authorization: Bearer SOME_BEARER_TOKEN
        body:
          username: SOME_USERNAME
          password: SOME_PASSWORD
        allowUnauthorized: true
        followRedirects: 1
```
From the configuration example above, is it possible for the following values ​​(`SOME_BEARER_TOKEN`,`SOME_USERNAME`,`SOME_PASSWORD` or other values ​​defined later) to be taken from the OS Environment Variables or other places?

The purpose of this question is that I intend to store these values ​​(`SOME_BEARER_TOKEN`,`SOME_USERNAME`,`SOME_PASSWORD` or other values ​​that are defined later) in another place that I can encrypt. Because I don't want to store these values ​​in plain text in the Configuration Yaml.

Thanks in advance for your help and response guys
