### DISCUSSION TITLE
Response body data in body post request

### DISCUSSION THREAD

**Discussion by rgraham7503** [hyperjumptech/monika#716] [General]
I do not see a way to use a previous response body data value in a new request body.
example:
probe id 1 gets an access token
probe id 2 wants to do an introspect on the access token from probe id 1.
Introspect endpoint requires 3 elements in the body
body:
    token: tokenvalue
    client_id: "xxxx"
    client_secret: "xxxx"

I am trying to use the access token from the response body of probe id 1 in the body of probe id2 
body:
    token: {{response.[0].data.access_token}}
    client_id: "xxxx"
    client_secret: "xxxx"

This spits out an error :
        _err = new cli_2.CLIError(input, options);
              ^
CLIError: missed comma between flow collection entries (75:31)

 72 |         timeout: 7000
 73 |         url: https://xxxx/oidc/endpoint/def ...
 74 |         body:
 75 |           token:  {{{response.[0].data.access_token}}}_

**Comment by dennypradipta** [comment]
Could you please provide the full configuration? You may redact sensitive values. And what version of Monika did you use?

If we take a look at the example:
```
probes:
   - id: '1'
     name: Probing Github
     description: simulate html form submission
     interval: 10
     requests:
       - method: GET
         url: https://reqres.in/api/users
         timeout: 7000
       - method: GET
         url: https://reqres.in/api/users/{{ responses.[0].data.data.[0].id }}
         timeout: 7000
     incidentThreshold: 3
     recoveryThreshold: 3
     alerts:
       - status-not-2xx
       - response-time-greater-than-2000-ms
```

There are two request inside a probe. The first request will return this:
```
{"page":1,"per_page":6,"total":12,"total_pages":2,"data":[{"id":1,"email":"george.bluth@reqres.in","first_name":"George","last_name":"Bluth","avatar":"https://reqres.in/img/faces/1-image.jpg"},{"id":2,"email":"janet.weaver@reqres.in","first_name":"Janet","last_name":"Weaver","avatar":"https://reqres.in/img/faces/2-image.jpg"},{"id":3,"email":"emma.wong@reqres.in","first_name":"Emma","last_name":"Wong","avatar":"https://reqres.in/img/faces/3-image.jpg"},{"id":4,"email":"eve.holt@reqres.in","first_name":"Eve","last_name":"Holt","avatar":"https://reqres.in/img/faces/4-image.jpg"},{"id":5,"email":"charles.morris@reqres.in","first_name":"Charles","last_name":"Morris","avatar":"https://reqres.in/img/faces/5-image.jpg"},{"id":6,"email":"tracey.ramos@reqres.in","first_name":"Tracey","last_name":"Ramos","avatar":"https://reqres.in/img/faces/6-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards server costs are appreciated!"}}
```

The second request will get the first ID of the data from the response body. So the second request will be reqres.in/api/users/1
```
{"data":{"id":1,"email":"george.bluth@reqres.in","first_name":"George","last_name":"Bluth","avatar":"https://reqres.in/img/faces/1-image.jpg"},"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards server costs are appreciated!"}}
```

**Comment by rgraham7503** [comment]
Hi @dennypradipta Here is the configuration file with two issues. 
body like this that does not work
body:
          token: {{ responses.[0].data.access_token }}
          client_id: "xxxxxxxx"
          client_secret: "xxxxxxxxx"

AND url that does not work.
method: DELETE
        timeout: 7000
        url: https://xxxxx.com/v2.0/Users/{{ responses.[1].data.id }}
Everything else in this file works. 
```
notifications:
  - id: desktop
    type: desktop
  - id: email notification
    type: smtp
    data:
      recipients: [xxxxxxx]
      hostname: xxxxxx
      port: 587
      username: xxxxxxx
      password: xxxxxx
probes:
  - id: isv_auth
    name: ISV Authentication Monitor
    interval: 30
    requests:
      - method: POST
        timeout: 7000
        url: https://xxxxx.com/v1.0/endpoint/default/token
        body:
          grant_type: "client_credentials"
          client_id: "xxxxxxxx"
          client_secret: "xxxxxxxxx"
        headers:
          Content-Type: application/x-www-form-urlencoded
        alerts:
          - query: response.time > 1200
            message: Login API Response time is {{ response.time }} ms, expecting less than 1200>
          - query: response.status < 200 or response.status > 299
            message: Target is not healthy. It has not been returning status code 2xx.
      - method: POST
        timeout: 7000
        url: https://xxxxx.com/v2.0/Users
        body:
          schemas:
            - urn:ietf:params:scim:schemas:core:2.0:User
            - urn:ietf:params:scim:schemas:extension:ibm:2.0:User
            - urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
            - urn:ietf:params:scim:schemas:extension:ibm:2.0:Notification
          userName: xxxxxxx
          title: Important person
          name:
            familyName: tester
            givenName: tester
            middleName: test
          urn:ietf:params:scim:schemas:extension:ibm:2.0:Notification:
            notifyType: NONE
          displayName: xxxxxx
          preferredLanguage: en-US
          active: true
          emails:
            - value: xxxxxxx
              type: work
          addresses:
            - locality: xxxx
              country: US
              type: work
              streetAddress: 111 my street. mytown, mystate
              postalCode: 'xxxxx'
              primary: true
              region: xx
          phoneNumbers:
            - value: 'xxxxxxxx'
              type: mobile
          urn:ietf:params:scim:schemas:extension:ibm:2.0:User:
            userCategory: regular
            twoFactorAuthentication: false
          urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:
            department: IT Engineering
            employeeNumber: '123234'
          password: xxxxxxxxx
        timeout: '5000'
        headers:
          Content-Type: application/scim+json
          Authorization: Bearer {{ responses.[0].data.access_token }}
        alerts:
          - query: response.status < 201 or response.status > 299
            message: Target is not healthy. It has not been returning status code 2xx.
          - query: response.time > 2800
            message: Login API Response time is {{ response.time }} ms, expecting less than 2000>
            
      - method: GET
        timeout: 7000
        url: https://xxxxx.com/v2.0/Users?filter=userName+eq+%22xxxxxx%22
        headers:
          Content-Type: application/x-www-form-urlencoded
          Authorization: Bearer {{ responses.[0].data.access_token }}
        alerts:
          - query: response.time > 2800
            message: Login API Response time is {{ response.time }} ms, expecting less than 2000>
          - query: response.status < 200 or response.status > 299
            message: Target is not healthy. It has not been returning status code 2xx.
            
      - method: DELETE
        timeout: 7000
        url: https://xxxxx.com/v2.0/Users/{{ responses.[1].data.id }}
        headers:
          notifyType: NONE
          Authorization: Bearer {{ responses.[0].data.access_token }}
        body: {}
        alerts:
          - query: response.time > 2800
            message: Login API Response time is {{ response.time }} ms, expecting less than 2000>
          - query: response.status != 204
            message: Login API Status code is not 204.
      - method: POST
        timeout: 7000
        url: https://xxxxx.com/v1.0/authnmethods/password/xxxxx?returnJwt=true
        body:
          username: "userthatwasjustcreated"
          password: "passwordofuserjustcreated"
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ responses.[0].data.access_token }}
        alerts:
          - query: response.time > 2800
            message: Login API Response time is {{ response.time }} ms, expecting less than 2000>
          - query: response.status != 200
            message: Login API Status code is not 200. Please check the service status!
      - method: POST
        timeout: 7000
        url: https://xxxxx.com/oidc/endpoint/default/introspect
        body:
          token: {{ responses.[0].data.access_token }}
          client_id: "xxxxxxxx"
          client_secret: "xxxxxxxxx"
        headers:
          Content-Type: application/x-www-form-urlencoded
        alerts:
          - query: response.time > 1200
            message: Login API Response time is {{ response.time }} ms, expecting less than 1200>
          - query: response.status < 200 or response.status > 299
            message: Target is not healthy. It has not been returning status code 2xx.
    incidentThreshold: 1
    recoveryThreshold: 1
```
