### DISCUSSION TITLE
Probes do not run in order

### DISCUSSION THREAD

**Discussion by rgraham7503** [hyperjumptech/monika#724] [General]
Is there a bug in the order in which Monika runs the probes? Or is it always random? My expectation was that its sequential?
I have 
probe 
 - id: 1 
 - name: myprobe A
 - id: 2
 - name: myprobe B
This is how it runs??
![image](https://user-images.githubusercontent.com/46932722/174810862-0ae1115d-5ebe-4d43-bc98-b3c3201ba62d.png)

**Comment by dennypradipta** [comment]
From what I know, the probe order does not run sequentially. The one that runs sequentially is the requests inside the probe.

This is because probes can have different intervals like so:
```
probes:
   - id: '1'
     name: Name of the probe
     description: Probe to check GET time
     interval: 10
     requests:
       - {}
     alerts: []
   - id: '2'
     name: Name of the probe 2
     description: Probe to check GET health
     interval: 15
     requests:
       - {}
     alerts: []
```

So the 1st probe will be run every 10 seconds, while the second probe will be run every 15 seconds.
