### DISCUSSION TITLE
Monitor non-http services

### DISCUSSION THREAD

**Discussion by guillaumemeyer** [hyperjumptech/monika#843] [Ideas]
Many services are providing non-http healthcheck methods, such as:
- [Redis](https://redis.io/commands/ping/)
- [Postgres](https://www.postgresql.org/docs/14/app-pg-isready.html)

It would be a nice addition to be able to monitor these services. Looks like it could be an extension of the TCP probes...

**Comment by dennypradipta** [comment]
Yeah, I've seen other services such as EaseProbe that could check MySQL/MongoDB/Redis/Postgres status. I think it's a nice idea

**Reply by guillaumemeyer** [reply]
Count me in for beta testing

**Reply by dennypradipta** [reply]
Hi @guillaumemeyer , we have added Redis, Postgres, and MongoDB monitoring. You could give it a try and let us know your experience :wink:

**Reply by guillaumemeyer** [reply]
Redis works great at the probe level, but the generated email notification is missing the probe-id and the URL (or another identifier):
![image](https://user-images.githubusercontent.com/1385518/206811245-8906c478-7f00-4f4b-823a-3e5d0a35da25.png)
For the URL it could probably be replaced by the redis host?

**Reply by guillaumemeyer** [reply]
Got a few questions regarding Redis probes...

**How to include the id or the name of the probe in the alert message?**
I have a probe defined as:
```yaml
  - id: redis
    name: Redis
    description: Redis
    interval: 1
    incidentThreshold: 1
    recoveryThreshold: 3
    redis:
      - host: $REDIS_HOST
        port: $REDIS_PORT
        password: $REDIS_PASSWORD
    alerts:
      - assertion: response.time > 500 # in milliseconds
        message: Redis response is slow, took {{ response.time }}ms
```
When the response time is exceeded, the message includes "Redis" as it's defined. But when another error occurs, such as "connect ECONNREFUSED", the error message send by email is just "Host cannot be reached", without any indication of the probe that failed...

**How to specify to use TLS for Redis connection?**
My suggestion would be to support a `uri` property (just like postgres) to specify a full connection string, from which we could specify `redis:` or `rediss:` as a prefix to enable/disable TLS connection.
