### ISSUE TITLE
Clean up code and example: remove references to 'id' property

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1001]
**Cleanup code and example**
1. Old codes and some examples still uses the 'id' property in the request field.
2. In the current documentation, the request field should not use an "id" property.

ex:  in `test/testConfigs/manyProbes.yml`
```
probes:
  - id: '1'
    requests:
      - id: 
        url: https://github.com
  - id: '2'
    requests:    
     - id: '2'
       url: https://example.com        
```
reference: https://monika.hyperjump.tech/guides/probes
