### ISSUE TITLE
SMTP notifications shoud be able to be configured without username/password

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#1012]
**Describe the bug**
I am trying to use the local postfix installation to send email notifications.
The server has no authentication configured and right now Monika expects the username and password to be provided when configuring this type of notification

**To Reproduce**
1. Configure an SMTP notification as follows
```
notifications:
  - id: email
    type: smtp
    data:
      hostname: 'localhost'
      username: ''
      password: ''
      port: 25
      recipients:
        - xxxx@xxxxx.xxx
```
2. Start Monika pointing to the config file
```
./monika --prometheus 3001 --status-notification=false -s -1 --config=monika.yml
```
3. Receive the following error
```
WARN: Failed to obtain location/ISP info. Got: Error: stun inaccessible
INFO: Updating config
ERROR: Username not found
```

**Expected behavior**
Authentication should not be required 

**Desktop (please complete the following information):**
 - OS: Rocky Linux
 - Version 8.6 (Green Obsidian)

**Additional context**
It should be possible to use local postfix installations to send email, since those are usually available and configured on enterprise servers as a way to send emails and most of the time they do not have authentication configured
