### ISSUE TITLE
PagerDuty notification not working properly

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#1015]
**Describe the bug**
When trying to configure a pagerduty integration, even after using the example from documentation, the config is deemed as invalid by monika

**To Reproduce**
1. Create a PagerDuty notification
```yaml
notifications:
  - id: pagerduty
    type: pagerduty
    data:
       key: aaaabbbbccccddddeeeeffffgggghhhh
       probeID: aaaabbbbccccddddeeeeffffgggghhhh
probes:
  - id: 'local-python'
    name: 'local-python-uuid'
    interval: 1
    requests:
      - url: http://0.0.0.0:8000/
```
3. Start Monika
```bash
./monika --prometheus 3001 --status-notification=false -s -1 --config=monika.yml`
```
```text
INFO: Monika is running from: Amsterdam...
INFO: Updating config
ERROR: PagerDuty notification: "value" must be an array
```

**Expected behavior**
Configuration should be parsed and considered valid, since it is being configured as shown in the documentation

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version: 13.2
