### ISSUE TITLE
Monika crashes when config is updated on disk

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#1016]
**Describe the bug**
When updating the config files used by Monika, while Monika is running, it crashes and had to be restarted.
This happens even if the configuration file is valid

**To Reproduce**
1. Create a PagerDuty notification
```yaml
probes:
  - id: 'local-python'
    name: 'local-python-uuid'
    interval: 1
    requests:
      - url: http://0.0.0.0:8000/
```
2. Start Monika
```bash
./monika --prometheus 3001 --status-notification=false -s -1 --config=monika.yml`
```
3. Update the config file with Monika running
```yaml
probes:
  - id: 'local-python'
    name: 'local-python-uuid'
    interval: 1
    requests:
      - url: http://0.0.0.0:8000/test
```
4. Monika crashes
```text
/snapshot/monika/node_modules/@oclif/core/lib/errors/index.js:29
        err = new cli_2.CLIError(input, options);
              ^

CLIError: A metric with the name monika_probes_total has already been registered.
    at Object.error (/snapshot/monika/node_modules/@oclif/core/lib/errors/index.js:29:15)
    at Monika.error (/snapshot/monika/node_modules/@oclif/core/lib/command.js:90:23)
    at Monika.run (/snapshot/monika/lib/index.js:196:18)
    at async Monika._run (/snapshot/monika/node_modules/@oclif/core/lib/command.js:67:22) {
  oclif: { exit: 1 },
  code: undefined
}
```

**Expected behavior**
It should be possible to update the config file while Monika is running without it crashing.
Updating the local config file should trigger a proper reload of Monika or leave it running until a manual restart is done.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version: 13.2
