### ISSUE TITLE
Crash with bad format config.yaml

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1036]
**Describe the bug**
Monika crashes with a bad formatted config.yaml

**To Reproduce**
1. Use the following config.yaml
```yaml
notifications:
  - id: desktop
    type: desktop

probes:
  - id: 6a31bcff-48f1-40b0-98aa-8c7610f4f428
    name: Google
    requests:
      url: https://www.google.com
      method: GET
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Response time is more than 2000ms
    incidentThreshold: 3
    recoveryThreshold: 3
```

3. Start monika with `monika -c test.yaml `

**Expected behavior**
1. An error warning due to bad format
2. Monika does not crash with a stack trace, but exits.

**Screenshots**

![image](https://user-images.githubusercontent.com/964106/232996861-75f65f04-6c25-4b4b-b3e6-6e891ed78f8a.png)

other bad formats did not cause a crash:

![image](https://user-images.githubusercontent.com/964106/233005441-5eeae330-cbfb-47da-b94b-f78b7bd5dd10.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version Pop!_OS
- Monika version: `@hyperjumptech/monika/1.15.2 linux-x64 node-v18.12.1`
