### ISSUE TITLE
InStatus Channel Seems Gone after v1.15.2

### ISSUE THREAD

**Issue by awcodify** [hyperjumptech/monika#1047]
**Describe the bug**
Got this error when enabling instatus notification type:
```
Notifications type is not allowed (instatus)
```

**To Reproduce**
Use this config:
```
probes:
- id: probe-01
  requests:
    - url: http://github.com/asdasda

- id: probe-02
  requests:
    - url: http://github.com

notifications:
- id: internal-instatus
  type: instatus
  data:
    apiKey: xxx
    pageID: xxx
```

I think, It appears that the instatus notification feature stopped working after this refactor https://github.com/hyperjumptech/monika/pull/1019/files#diff-a4c29782d941cc4d914b2715f202ac340a4ef1988c812c04e38e8f8480225a69
