### ISSUE TITLE
Wrong default alerts for non-HTTP probe

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#1062]
**Describe the bug**

When probing a non-http probe, like postgres, without specifying the alerts, e.g. using the following config:

```yaml
probes:
  - id: 'postgres-01'
    name: database health
    description: ensure db health
    interval: 10 # in seconds
    incidentThreshold: 3
    postgres:
      - host: 127.0.0.1
        port: 5432
        user: user
        password: password
        database: mydb
```

Monika "sanitizes" the probe by adding some default values including the `alerts`. However, the default value for the `alerts` don't make sense for non-HTTP probe, namely Monika will add HTTP-related alerts like the following:

```javascript
{
  id: 'postgres-01',
  name: 'database health',
  description: 'ensure db health',
  interval: 10,
  incidentThreshold: 3,
  postgres: [
    {
      host: '127.0.0.1',
      port: 5432,
      user: 'user',
      password: 'password',
      database: 'mydb'
    }
  ],
  requests: [],
  alerts: [
    {
      assertion: 'response.status < 200 or response.status > 299',
      message: 'HTTP Status is {{ response.status }}, expecting 200'
    },
    {
      assertion: 'response.time > 2000',
      message: 'Response time is {{ response.time }}ms, expecting less than 2000ms'
    }
  ],
  recoveryThreshold: 5
}
```

This results in weird incident notification message, e.g., in Slack:

<img width="480" alt="Screenshot 2023-06-14 at 22 56 32" src="https://github.com/hyperjumptech/monika/assets/311343/d1c359ec-b261-41f4-9bf8-ab55a1c5ef29">

**To Reproduce**
1. Use the config I mentioned above.
2. Run monika with that config.
3. See the unrelated notifications.

**Expected behavior**
A clearer and related incident/recovery messages.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Version commit 3bb855b6bfe4335106968b046bfe7a609a9bec88

**Additional context**
I only checked the postgres but pretty sure this bug applies to all non-http probe.
