### ISSUE TITLE
Monika crashes when some of the probe is removed from the configuration

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1066]
**Describe the bug**
Monika crashes when some of the probe is removed from the configuration.

**To Reproduce**
1. Run the following config until the probe is running
```yaml
probes:
  - id: "Google"
    requests:
      - url: https://google.com
  - id: "YouTube"
    requests:
      - url: https://youtube.com
  - id: "Facebook"
    requests:
      - url: https://facebook.com
  - id: "Twiter"
    requests:
      - url: https://twitter.com
  - id: "Instagram"
    requests:
      - url: https://instagram.com
  - id: "Baidu"
    requests:
      - url: https://baidu.com
  - id: "Wikipedia"
    requests:
      - url: https://wikipedia.org
  - id: "Yandex"
    requests:
      - url: https://yandex.ru
  - id: "Yahoo"
    requests:
      - url: https://yahoo.com
  - id: "WhatsApp"
    requests:
      - url: https://whatsapp.com
```
2. Remove nine of the probe and save

**Expected behavior**
Monika restarting with the new config

**Video**

https://github.com/hyperjumptech/monika/assets/15191978/8525db89-2221-443d-85e4-7e272acb4f57

**Desktop (please complete the following information):**
 - OS: [e.g. Pop!_OS]
 - Version [e.g. 22.04]
 - Monika version: Commit [2bb9ad7](thttps://github.com/hyperjumptech/monika/commit/2bb9ad7)
