### ISSUE TITLE
Default maxRedirects too shallow

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1069]
**Describe the bug**
1. When probing a url with redirect, monika returns error service down instead of following redirect

**To Reproduce**
1. Use the following config.yaml
```yaml
probes:
  - id: 'http-1'
    name: 'status-200-test'
    requests:
      - url: https://www.spotify.com
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
    incidentThreshold: 3
    recoveryThreshold: 3

notifications:
  - id: desktop
    type: desktop
```
3. Run the probes `monka -c config.yaml`

**Expected behavior**
1. Expect probe to work.
2. Expect some redirects to work

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/964106/d45c32fc-4ee2-474a-ab7a-4f78fa7daafb)

**Desktop (please complete the following information):**
 - OS: PopOS 22.0 LTS
 - Monika: `@hyperjumptech/monika/1.15.3 linux-x64 node-v18.16.0`
