### ISSUE TITLE
Requests info is empty on non HTTP probe

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1078]
**Describe the bug**
Requests info is empty on non HTTP probe

**To Reproduce**
1. Run a PostgreSQL service. Run `cd dev && docker compose up`
2. Run Monika with the following configuration and use verbose flag. Run `npm start -- --verbose`

```yaml
probes:
  - id: postgres
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    postgres:
      - uri: postgres://postgres_user:postgres_password@localhost:5432/postgres_db
```

**Expected behavior**
Probe info should be displayed

**Screenshots**
![verbose-mode-with-empty-requests](https://github.com/hyperjumptech/monika/assets/15191978/99c11ed8-8317-422d-81b5-9b5848a91e83)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version: 22.04
