### ISSUE TITLE
Monika Crash When Running Non HTTP Probe with Prometheus Flag

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1081]
**Describe the bug**
Monika crash when running non http probe with Prometheus flag

**To Reproduce**
1. Run local postgreSQL. Run `cd dev && docker compose up`
2. Run Monika with the following config and prometheus flag. Run `npm start -- --prometheus 3001`

```yaml
probes:
  - id: postgres
    interval: 2
    incidentThreshold: 1
    recoveryThreshold: 1
    postgres:
      - uri: postgres://postgres_user:postgres_password@localhost:5432/postgres_db
```

**Expected behavior**
Monika probe the postgreSQL and display the metrics on the prometheus endpoint

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/15191978/2677f4fb-3f83-4517-8c51-b0e6b1ff25fa)

**Desktop (please complete the following information):**
 - OS: [e.g. Pop!_OS]
 - Version [e.g. 22.04]
