### ISSUE TITLE
Repeat 1 doesn't exit when the probe is not accessible

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#1164]
**Describe the bug**
Monika doesn't exit when the probe in the configuration is not accessible. Instead, it keeps retrying.

**To Reproduce**
1. Run monika from the main branch: `npm run start -- -c ./monika.yml -r 1`
2. Use the following configuration:

```yaml
probes:
  - id: '1'
    name: Localhost
    description: Multiple
    requests:
      - url: http://localhost:3000
```

**Expected behavior**
Monika should exit even when the probe cannot be reached. 

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/311343/6102bd38-5485-4c18-9bb8-be1513123355)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0 (23A344)
 - Version 72302026976793f23f58e10aabff6ac4baf57b07
 - Node v18.17.1
