### ISSUE TITLE
Alert Assertion Validation Does not Working as Expected

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1177]
**Describe the bug**
Monika crashes when the alert assertion value is invalid.

**To Reproduce**
Run Monika with the following configuration:

```yaml
probes:
  - id: '1'
    requests:
      - url: https://github.com
        alerts:
          - assertion: response.size >= 10000 ms
            message: Response size is {{ response.size }}, expecting less than 10000
```

**Expected behavior**
Monika gives a message to inform that alert assertion is invalid and stop. In Symon mode, Monika skips the probe that has invalid alert assertion and continues to run other probe.

**Screenshots**
![b8d8210f-4306-4244-939e-460753f26c88](https://github.com/hyperjumptech/monika/assets/15191978/88f056d2-fb1b-4996-b69c-4c690433339e)

**Desktop (please complete the following information):**

- OS: [e.g. Pop!_OS]
- Version [e.g. 22.04]
