### ISSUE TITLE
Snap version fails to run

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1255]
**Describe the bug**
1. Running snap version of monika fails

**To Reproduce**

1. Install the snap version of Monika `sudo snap install monika --edge`
2. Verify that it is the snap version, issue the command `which monika` should return `/bin/snap/monika`
3. Next issue the following command 'monika -c test.yaml'

test.yaml configuration
```yaml
probes:
  - id: 'mock-1'
    name: 'local-test'
    requests:
      - url: http://0.0.0.0:7001/v1/hello2
    alerts:
      - assertion: response.status != 200
        message: message 11

notifications:
  - id: desktop
    type: desktop

```

**Expected behavior**
- Should be able to access test.yaml
- Should be able to probe the targets in test.yaml
- Should be able to detect connectivity issues with the probe and generate notifications

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/964106/ba7fd95d-9ff3-4ccb-9f0c-33ff1fcc5db9)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- Distro: POP_OS!
- Monika: v1.19.0

**Additional context**
