### ISSUE TITLE
Configurable Follow HTTP Redirect for Probe Requests

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1259]
Currently, Monika only supports a globally configurable follow HTTP redirect. To enhance flexibility, each request should be able to configure its own follow HTTP redirect. The following is a sample configuration to implement the follow HTTP redirect in a request.

```yaml
probes:
  - id: "1"
    requests:
      - url: https://example.com
        followRedirects: 0
```

The rule must be consistent with the [`follow-redirects`](https://monika.hyperjump.tech/guides/cli-options#follow-redirects) flag. If it is set to empty, it should use the value of the `follow-redirects` flag.
