### ISSUE TITLE
Make TLS Probe Independent

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1261]
The TLS checker requires the HTTP probe configuration to run, as demonstrated in [the documentation example](https://monika.hyperjump.tech/guides/tls-checkers).

```yaml
probes:
  - requests:
      - url: http://example.com
certificate:
  domains:
    - example.com
    - expired.badssl.com
    - domain: example.com
      options:
        path: '/foo'
  reminder: 30
```

It should be capable of running independently with the following configuration.

```yaml
 certificate:
   domains:
     - example.com
     - expired.badssl.com
     - domain: example.com
       options:
         path: '/foo'
   reminder: 30
```
