### ISSUE TITLE
--ignoreInvalidTLS flag is not working

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#1327]
**Describe the bug**
When using --ignoreInvalidTLS, it should not throw ELEAFSIGNATURE error when probing websites with self signed SSL.

**To Reproduce**

1. Create a monika config that points to `https://www.banksinarmas.com/PersonalBanking/loginCustomer.do`
```yml
probes:
  - id: '1'
    name: Example
    interval: 1
    requests:
      - url: https://www.banksinarmas.com/PersonalBanking/loginCustomer.do
        timeout: 30
    alerts:
      - assertion: response.status == 500
        message: API is not working!
notifications:
  - id: '1'
    type: desktop
```
3. Run Monika with the config

**Expected behavior**
It should work

**Screenshots**
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/77cd9877-76d5-464b-8c30-3330ac4a1bab">

**Desktop (please complete the following information):**

MacOS Ventura

**Additional context**
N/A
