### ISSUE TITLE
Failed to read assertion Error

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1330]
**Describe the bug**
Getting some error message "Failed request assertion is not found" when probing.

**To Reproduce**
1. Use the following config.yaml
```yaml
probes:
  - id: 'http-1'
    name: 'mock-test'
    requests:
      - url: http://0.0.0.0:7001/v1/hello
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
      - assertion: response.ime > 2000
        message: Too sloow
```

2. Start probing using: `npm start -- -c config.yaml`
3. Start your local mock server
4. Then disable/turn off the mock server

**Expected behavior**
1. Assertion exist, should have no problem finding it even when connection is refused

**Screenshots**
![image](https://github.com/user-attachments/assets/332a31a2-c5c7-499a-b651-eff2a7f59114)

**Desktop (please complete the following information):**

- OS: WIndows 11 and WSL (Ubuntu 24.04 LTS)
- Lateest monika from main branch

**Additional context**
Seems to appear when disconnected/ERCONNREFUSED error

**Comment by dennypradipta** [comment]
@syamsudotdev unfortunately this bug rises again.

Try this config:
```yaml
notifications:
  - id: 97a34fe1-73ff-4c93-93d6-df6aea9e44c8
    type: desktop
probes:
  - id: 5d115693-4264-4ce8-bc03-6c228b38e3a6
    name: BadSSL
    description: ''
    interval: 10
    requests:
      - url: https://self-signed.badssl.com/
        body: {}
        timeout: 10000
        headers: {}
        method: GET
    incidentThreshold: 5
    recoveryThreshold: 5
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: Target is not healthy. It has not been returning status code 2xx.
      - assertion: response.time > 2000
        message: >-
          Target is not healthy. The response time has been greater than 2000
          ms.
```

Then run

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/e88ab308-2673-4592-b363-69a149f54f17" />
