### ISSUE TITLE
Incorrect prometheus `monika_probe_running_total` metric 

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1335]
**Describe the bug**
The `monika_probe_running_total` metric shows incorrect result

**To Reproduce**

1. Using the following config.yaml
```yaml
probes:
  - id: 'mock-1'
    name: 'local-test-test'
    requests:
      - url: http://0.0.0.0:7001/v1/hello
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200

  - id: 'http-1'
    name: 'status-200-test'
    requests:
      - url: https://httpbin.org/status/200
        method: GET
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Too slow
```
2. Run monika on `npm start -- --prometheus 3001 -c config.yaml`
3. Start your target/mock server (mock-1)
4. Go to `localhost:3001/metric` on your browser
5. After a few minutes disable/turn off the target/mock server (mock-1)

**Expected behavior**
The metric `monika_probe_running_total` should show 0 for the disabled probe and 1 for enabled

**Screenshots**
both probes running:
![image](https://github.com/user-attachments/assets/e0754be7-89ac-4ef3-acfa-79e11d098869)

when mock probe is disabled:
![image](https://github.com/user-attachments/assets/e5637ca1-5a0c-4da5-936e-736b5e42c2b8)

**Desktop (please complete the following information):**

- OS: Ubuntu LTS 24.04 as WSL on Windows 11
- Version: Monika in main branch / version 1.21.x
