### ISSUE TITLE
The metric `monika_probe_result` displaying incorrectly

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1336]
**Describe the bug**
The `monika_probe_result ` metric is stuck on 1 / success

**To Reproduce**

1. Using the following config.yaml
```yaml
probes:
  - id: 'mock-1'
    name: 'local-test-test'
    requests:
      - url: http://0.0.0.0:7001/v1/hello
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200

  - id: 'http-1'
    name: 'status-200-test'
    requests:
      - url: https://httpbin.org/status/200
        method: GET
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Too slow
```
2. Run monika on `npm start -- --prometheus 3001 -c config.yaml`
3. Start your target/mock server (mock-1)
4. Go to `localhost:3001/metric` on your browser
5. After a few minutes disable/turn off the target/mock server (mock-1)

**Expected behavior**
The metric `monika_probe_result ` should show 0 for a failed probe and 1 for success

**Screenshots**
both probes running and when mock probe is disabled:
![image](https://github.com/user-attachments/assets/f233c677-b0ae-4868-b01e-69fe23a4fe01)

**Desktop (please complete the following information):**

- OS: Ubuntu LTS 24.04 as WSL on Windows 11
- Version: Monika in main branch / version 1.21.x
