### ISSUE TITLE
SMTP Notification is broken

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#1343]
**Describe the bug**

Notification using SMTP fails to send

**To Reproduce**

1. Setup an SMTP notificaiton channel, using config.yaml:
````yaml
probes:  

  - id: 'http-1'
    name: 'status-401-test'
    requests:
      - url: https://httpbin.org/status/401
        method: PATCH
    alerts:
      - assertion: response.status < 200 or response.status > 308
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Too sloow
        
notifications:
  - id: smtp-maitrap
    type: smtp
    data:
      recipients: ['test@example.com']
      hostname: smtp.mailtrap.io
      port: 2525
      username: 'user'
      password: 'password'
````
2. To start type: 'npm start -- -c config.yaml'
3. Check smtp inbox for notifications

**Expected behavior**
Expect notifications from SMTP channel to be received.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4e69f3d7-36d3-4a61-b47a-985a43c2da36)

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04 LTS on WSL, Windows 11
- Monika Version: main branch (this test ran on commit id: `ffc8e9b9619205fc4e164fe9586fb5f05e27d039`)
