### ISSUE TITLE
wrong reading config file

### ISSUE THREAD

**Issue by lukman7788** [hyperjumptech/monika#1345]
**Describe the bug**
Running Monika with the Insomnia and Postman argument, the program reads `monika.yml` instead of the filename provided in the next argument

**To Reproduce**

1. Make a file monika.yml
```yaml
notifications:
  - id: c97e1ae7-5022-485d-a51e-23734edfd0b3
    type: desktop
probes:
   - id: ping_test
     name: ping_test
     description: requesting icmp ping
     interval: 1
     ping:
       - uri: google.com
```
2. Make a file insomnia.yaml
```yaml
_type: export
__export_format: 4
__export_date: 2025-01-24T05:27:52.241Z
__export_source: insomnia.desktop.app:v10.3.0
resources:
  - _id: req_c0918b7d2b4a424aa1dab19e1f8822be
    parentId: wrk_78c651d0d2ef4bbeba27ca5d3d49909d
    modified: 1737696321173
    created: 1713329870680
    url: https://insomnia.rest/
    name: insomnia
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: ""
    metaSortKey: -1713329870680
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: wrk_78c651d0d2ef4bbeba27ca5d3d49909d
    parentId: null
    modified: 1737696376394
    created: 1713329864652
    name: Random
    description: ""
    scope: collection
    _type: workspace
  - _id: env_83f4449dc03cf89614238cf944bebacb7adb6662
    parentId: wrk_78c651d0d2ef4bbeba27ca5d3d49909d
    modified: 1713329864656
    created: 1713329864656
    name: Base Environment
    data: {}
    dataPropertyOrder: null
    color: null
    isPrivate: false
    metaSortKey: 1713329864656
    _type: environment
  - _id: jar_83f4449dc03cf89614238cf944bebacb7adb6662
    parentId: wrk_78c651d0d2ef4bbeba27ca5d3d49909d
    modified: 1713329864657
    created: 1713329864657
    name: Default Jar
    cookies: []
    _type: cookie_jar

```
2. run  `monika -I insomnia.yaml`
3. program will read `monika.yml`
4. run `monika --config monika.yml -I insomnia.yaml` only read on monika.yml only

**Expected behavior**
program will read config from insomnia.yaml

**Screenshots**

<img width="922" alt="Image" src="https://github.com/user-attachments/assets/1d83e17a-eca7-4f53-ae12-764df25f6dd2" />

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.5 LTS

**Additional context**
