### ISSUE TITLE
Alerts assertion not working as expected

### ISSUE THREAD

**Issue by o3webmaster** [hyperjumptech/monika#1359]
I have tried the given doc and examples in may ways (with all possible combinitions) but I could not generate two separate type of messages based on the assertion. Form the console logs it appears the actual / relevant assertion does get evaluated/executes but system is not able to analyze whether it need to send the alert or not and hence doesn't generate the alert.
However, if I have only one assertion (fulfilling all states) then it works and generates alert for the service when its state changes (Up, down). It also works if I do not have any details given in Alerts & assertion specified:

`  - id: 200-app-identity`
`    name: Fusion Web Portal Login Service (Production)`
`    interval: 10    # in seconds`
`    requests:`
`      - url: https://mysampledomain.com/api/v1/user`
`        method: POST`
`        body: {"payload":"{\"email\":\"abc@abc.com\"}"}`
`        timeout: 5000    # in milliseconds`
`    incidentThreshold: 3`
`    recoveryThreshold: 3`
`    alerts:`
`      - assertion: response.status != 200 or response.time >=4000`
`        message: '[💔] System/Service Unhealthy: Fusion Web Portal response received instead of 200 in {{ response.time }} time.'`
`      - assertion: response.status == 200`
`        message: '[👍] System/Service Restored: Fusion Web Portal login API has recovered and has been accessible for the past 50 seconds.' `

This example only works once when launched with relevant alert message but later on it never intimates/alerts if the subjective service state changes (down / up).

**Comment by dennypradipta** [comment]
Hi @o3webmaster thank you for using Monika!

Basically, alerts are meant to detect when a service is down or unhealthy. If response.status == 200, that’s the expected behavior, meaning the service is up and running normally. So, you don’t need to define that as an alert assertion.

If you do define response.status == 200 in the alerts section, it will trigger an alert every time the service is healthy — which is not what you want. That would result in false positives.

Instead, define alert conditions only for the unhealthy states — for example:
```yaml
alerts:
  - assertion: response.status != 200
    message: '[💔] System/Service Unhealthy: Fusion Web Portal responded with {{ response.status }} instead of 200.'
```

As a suggestion, it’s better to separate alerts for response status and response time. That way, you’ll get clearer messages and can identify the root cause more easily — whether it’s a failed request or just a slow one.

```yaml
alerts:
  - assertion: response.status != 200
    message: '[💔] System/Service Unhealthy: Fusion Web Portal responded with {{ response.status }} instead of 200.'
  - assertion: response.time >= 4000
    message: '[🐢] Performance Issue: Fusion Web Portal responded in {{ response.time }}ms (threshold: 4000ms).'
```

You don’t want to get an alert about response time but see a message that talks about status code, right? Keeping them separate helps you debug faster.

I hope it helps!
