### ISSUE TITLE
Cannot create an alert if response body is empty

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#428]
**Describe the bug**
Cannot create an alert for checking if response body is empty

**To Reproduce**
1. Use this config:
```
notifications:
  - id: desktop
    type: desktop
probes:
  - id: sample_1
    name: Sample Request
    requests:
      - method: GET
        url: https://reqres.in/api/users/23
    alerts:
      - query: response.time > 200
        message: Response time is {{ response.time }} ms, expecting less than 200ms
      - query: response.status != 200
        message: Status code is not 200. Did you fix something in production?!
      - query: response.body == "{}"
        message: Hmm, I expect the ID to be 23.
    incidentThreshold: 2
    recoveryThreshold: 2
```

**Expected behavior**
It should notify that the response body is null or empty object

**Screenshots**
It only shows 2 notifications instead of 3
![Screenshot_20210921_102308](https://user-images.githubusercontent.com/16670475/134106811-8d9e5c56-8e59-4cc6-906b-734977c15e55.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**
Uses Monika v1.6.0
