### ISSUE TITLE
Cannot find default monika.json/yml file on v1.6.1

### ISSUE THREAD

**Issue by samsunoor** [hyperjumptech/monika#437]
**Describe the bug**
Provided current working directory have `monika.json`.
`monika` (without explicit `-c/--c`) will complain not being able to find the `monika.json/monika.yml`

**To Reproduce**
1. Create file `monika.yml`
```
probes:
  - id: '1'
    requests:
      - url: http://github.com
```
2. Run `monika` from the same directory
3. Monika will return error

**Expected behavior**
Should automatically use `{CWD}/monika.yml` and parse `monika.yml`.

**Screenshots**
![image](https://user-images.githubusercontent.com/9563873/134469486-9bf3f358-14cd-4aa6-8759-2185f9544714.png)
