### ISSUE TITLE
[REGRESSION] Monika does not auto reload on file change

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#441]
**Describe the bug**
Monika does not auto reload anymore when config file changes.

**To Reproduce**

Use this config:

```yaml
probes:
  - id: '1'
    incidentThreshold: 5
    recoveryThreshold: 5
    requests:
      - url: http://localhost:3000
notifications:
  - id: unique-id-monika-notif,
    type: desktop
```

Run `monika -c monika.yml`, then change the file say the incidentThreshold.

**Expected behavior**

Monika should restart automatically using the new config.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version @hyperjumptech/monika/1.6.1 darwin-x64 node-v14.16.0
