### ISSUE TITLE
Windows Desktop Notification is Not Working

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#453]
**Describe the bug**
When an incident or recovery happens while running Monika, desktop notification does not work in Windows 

**To Reproduce**
Update your Monika to v1.6.2 first by `npm install -g @hyperjumptech/monika` or download the binary in the release page.

1. Create a configuration file called config.yml:
```
notifications:
  - id: desktop
    type: desktop
probes:
  - id: sample_1
    name: Sample Request
    requests:
      - method: GET
        url: https://reqres.in/api/users/23
    alerts:
      - query: response.time > 200
        message: Response time is {{ response.time }} ms, expecting less than 200ms
      - query: response.status != 200
        message: Status code is not 200. I think their service is down.
      - query: isEmpty(response.body)
        message: Response body should not be empty!
    incidentThreshold: 2
    recoveryThreshold: 2
```
2. With Monika installed, run `monika -c config.yml`

**Expected behavior**
When there is any incidents or recoveries, it should sent you the desktop notifications

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
- You can modify the file in ./src/components/notification/channel/desktop.ts
- Please do not use external libraries such as `node-notifier` as it may breaks the packaging.
