### ISSUE TITLE
Prettify Email Notification

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#454]
**Describe the issue**
Notification sent using email is only a one-liner text. It should be prettier.

**To Reproduce**
Prerequisites:
- Use SMTP from https://mailnest.io if you didn't have any SMTP server available.
- Install Monika v1.6.2 first by running `npm install -g @hyperjumptech/monika` or download the binary in the release page

1. Create a new file called config.yml:
```
notifications:
  - id: unique-id-smtp
    type: smtp
    data:
      recipients:
        - YOUR_EMAIL_ADDRESS_HERE
      hostname: smtp.gmail.com
      port: 587
      username: YOUR_GMAIL_ACCOUNT
      password: YOUR_GMAIL_PASSWORD_OR_APP_PASSWORD
probes:
  - id: sample_1
    name: Sample Request
    requests:
      - method: GET
        url: https://reqres.in/api/users/23
    alerts:
      - query: response.time > 200
        message: Response time is {{ response.time }} ms, expecting less than 200ms
      - query: response.status != 200
        message: Status code is not 200. I think their service is down.
      - query: isEmpty(response.body)
        message: Response body should not be empty!
    incidentThreshold: 2
    recoveryThreshold: 2
```
2. Run Monika by running `monika -c config.yml`

**Expected behavior**
It should be prettier, you can use [Mailgen](https://www.npmjs.com/package/mailgen)

**Screenshots**
Currently it is like this:
![image](https://user-images.githubusercontent.com/16670475/135552454-4f51385b-4ae0-4cb2-ad24-7d2cb49b03d3.png)

**Additional context**
- You can use [Mailgen](https://www.npmjs.com/package/mailgen)
- Check the src/components/notification/index.ts and src/components/notification/channel/smtp.ts
