### ISSUE TITLE
Prettify and Fix Slack Recovery Message

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#456]
**Describe the bug**
1. Slack notification is not pretty

**To Reproduce**
Prerequisites:
- Install Monika v1.6.2 by running `npm install -g @hyperjumptech/monika` or download the binary in the release page.
- (You need a Slack Incoming Webhook URL)[https://api.slack.com/messaging/webhooks]

1. Create a file called config.yml:
```
notifications:
 id: unique-id-slack
 type: slack  
 data:
   url: https://YOUR_SLACK_INCOMING_WEBHOOK_URL
probes:
  - id: sample_1
    name: Sample Request
    requests:
      - method: GET
        url: https://reqres.in/api/users/23
    alerts:
      - query: response.time > 200
        message: Response time is {{ response.time }} ms, expecting less than 200ms
      - query: response.status != 200
        message: Status code is not 200. I think their service is down.
      - query: isEmpty(response.body)
        message: Response body should not be empty!
    incidentThreshold: 2
    recoveryThreshold: 2
```
2. Run Monika by running `monika -c config.yml`

**Expected behavior**
1. It should be pretty enough
2. It should display correct recovery message

Here is an example of Teams version:
![image](https://user-images.githubusercontent.com/16670475/135554284-097b99cb-4898-4fa2-a2e3-d008e2746c8d.png)

**Screenshots**
Currently, notifications sent are like this:
![image](https://user-images.githubusercontent.com/16670475/135553898-74d3abd4-0d0e-4417-b386-aec67433da67.png)

**Additional context**
- Check out the `/src/components/notification/index.ts and /src/components/notification/channel/slack.ts`
