### ISSUE TITLE
Mailgen Emails Breaks in iOS Email App when there is more than 1 recipients

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#465]
**Describe the bug**
Seems like the email is not full-width.

**To Reproduce**
Prerequisites:
- Install Monika v1.6.3 first by running `npm install -g @hyperjumptech/monika` or download the binary in the release page
- Make sure to setup your email in your iOS Email app

1. Create a new file called config.yml:
```
notifications:
  - id: unique-id-smtp
    type: smtp
    data:
      recipients:
        - YOUR_EMAIL_ADDRESS_HERE
      hostname: YOUR_SMTP_HOST
      port: YOUR_SMTP_PORT
      username: YOUR_SMTP_ACCOUNT
      password: YOUR_SMTP_PASSWORD
probes:
  - id: sample_1
    name: Sample Request
    requests:
      - method: GET
        url: https://reqres.in/api/users/23
    alerts:
      - query: response.time > 200
        message: Response time is {{ response.time }} ms, expecting less than 200ms
      - query: response.status != 200
        message: Status code is not 200. I think their service is down.
      - query: isEmpty(response.body)
        message: Response body should not be empty!
    incidentThreshold: 1
    recoveryThreshold: 1
```
2. Run Monika by running `monika -c config.yml`
3. Check your email in iOS Email App

**Expected behavior**
It should display the email in full-width

**Screenshots**
![image](https://user-images.githubusercontent.com/16670475/136512602-507ace81-41a0-4c72-aa2e-45e902deb6f7.png)

**Desktop (please complete the following information):**
 - OS: iOS 15

**Additional context**
Please check https://www.npmjs.com/package/mailgen for better context. Probably test other themes
