### ISSUE TITLE
Empty message in incident / recovery notification

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#476]
**Describe the bug**
In the incident / recovery email sent via SMTP and in Slack, the message is empty which makes it confusing what the incident or recovery was. 

**To Reproduce**

1. Use config below.
2. Run `monika -c monika.yml`
3. See the email notification.

```
# monika.yml
notifications:
  - id: unique-id-smtp
    type: smtp
    data:
      recipients:
        - <someemail>
      hostname: smtp.gmail.com
      port: 587
      username: <gmailusername>
      password:  <gmailpassword>
probes:
  - id: 'monika-localhost-2'
    incidentThreshold: 5
    recoveryThreshold: 5
    requests:
      - url: http://localhost:3000
    alerts:
      - query: response.status < 200 or response.status > 299
      - query: response.time > 2000
```

**Expected behavior**
The message should indicates which alert causes the incident and recoveries. 

**Screenshots**

<img width="580" alt="Screenshot 2021-10-12 at 21 52 21" src="https://user-images.githubusercontent.com/311343/137021005-72075ad9-dbb5-4489-a167-f832a6ce11d8.png">

![IMG_8633](https://user-images.githubusercontent.com/311343/137021024-2c2c0ad0-731d-4f91-95ce-e49f96d38c65.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.6.3 and 1.6.2

**Notes**
Haven't checked in other notification channels, but probably it's the same case?

**Comment by armedi** [comment]
In the config above, no message is defined for the alerts. You might want to add message to alert like:

```yaml
    alerts:
      - query: response.status < 200 or response.status > 299
        message: Response is not OK
      - query: response.time > 2000
        message: Response time too slow
```

Can you suggest the message format for when the configuration is empty? @nicnocquee
