### ISSUE TITLE
Ping (ICMP) support

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#551]
It'd be great if Monika can also ping a host. We can add a new `ping` property in the `request` 

Example,

```yaml
probes:
  - id: probe-1
    name: Probe Name
    description: Landing page of Probe
    interval: 20
    requests:
      - host: https://hyperjump.tech
         ping: true
```
