### ISSUE TITLE
TCP server probing

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#568]
There is a request to support probing a TCP server. I'm thinking to add this in the configuration

```yml
probes:
  - id: '1'
    name: Name of the probe
    description: Probe to check TCP server
    interval: 30
    timeout: 10
    socket:
      host: <ip>
      port: <port number>
      data: <string to send>
   alerts:
     - query: response.size > 0
       message: Response size is {{ response.size }}, expecting more than 0
 
```
