### ISSUE TITLE
ERROR: Cannot read property 'state' of undefined when running Monika configuration with Request Alerts, but it's fine with Probe Alerts

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#603]
**Describe the bug**
When defining request alerts, it shows an error "ERROR: Cannot read property 'state' of undefined"

**To Reproduce**
1. Use this config:
```yaml
notifications:
  - id: desktop
    type: desktop
probes:
  - id: ping_test
    name: ping_test
    description: requesting icmp ping
    interval: 10
    requests:
      - url: https://google.com
        ping: true
      - url: https://reqres.in/api/users
        alerts: 
          - query: response.status != 200
            message: Status is not 200
          - query: response.time > 2000
            message: Request took longer than 2 seconds
    alerts:
      - query: response.time > 10000
        message: Please check your internet connection
    incidentThreshold: 1
    recoveryThreshold: 1
```

**Expected behavior**
It works perfectly just like using this config:
```yaml
notifications:
  - id: desktop
    type: desktop
probes:
  - id: ping_test
    name: ping_test
    description: requesting icmp ping
    interval: 10
    requests:
      - url: https://google.com
        ping: true
      - url: https://reqres.in/api/users
    alerts:
      - query: response.time > 10000
        message: Please check your internet connection
    incidentThreshold: 1
    recoveryThreshold: 1

```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**

**Comment by sapiderman** [comment]
Just briefly troubleshooting this.. This seems like a chaining issue rather than an ICMP Ping issue. Still looking at it.

**Comment by sapiderman** [comment]
this seems to be the simplest config to get the error.

```yaml
probes:
  - id: 'test-1'
    name: test-1 probe
    description: status returns 200
    interval: 5
    requests:
      - url: https://httpbin.org/status/200
    alerts:
      - query: response.status != 200
        message: response status message

  - id: 'test-2'
    name: test-2 probe
    description: return 200
    interval: 5
    requests:
      - url: https://httpbin.org/status/200

notifications:
  - id: my-desktop-notif
    type: desktop
 ```
