### ISSUE TITLE
TCP property bug

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#625]
**Describe the bug**
Property error on tcp request

**To Reproduce**
Steps to reproduce use the config:
```yaml
probes:
  - id: "random-id"
    socket:
      host: localhost
      port: 3333
      data: Hello from Monika
```
run `monika -c tcp-test.yml`

**Expected behavior**
should run without error

**Screenshots**
![image](https://user-images.githubusercontent.com/964106/157817445-94455597-2318-4b04-91ee-a1d020886c75.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version 21.10 impish
