### ISSUE TITLE
Unknown Properties Error in Monika

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#656]
**Describe the bug**
When running  monika, a wierd error shows up: "ERROR: Cannot read properties of undefined (reading 'state')"

**To Reproduce**
1. Run Monika with a config file `Monika -c test.yml -s 0`
2. The test YAML file is below
```
probes:
  - id: 'test-2'
    name: test-1 probe
    description: status returns 200
    interval: 5
    requests:
      - url: https://httpbin.org/status/200
    alerts:
      - query: response.status != 200
        message: response status message
    incidentThreshold: 3
    recoveryThreshold: 3

  - id: 'test-2'
    name: test-2 probe
    description: return 200
    interval: 5
    requests:
      - url: https://httpbin.org/status/200
        method: GET
        timeout: 3000
    alerts:
      - query: response.status < 300
        message: response status message
    incidentThreshold: 5
    recoveryThreshold: 5

notifications:
  - id: my-desktop-notif
    type: desktop
```

**Expected behavior**
No unexpalined error should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/964106/165710252-e2a82476-dd78-4172-a1a6-403f93b4762b.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 22.04
 - Monika version: @hyperjumptech/monika/1.7.2 linux-x64 node-v16.15.0
