### ISSUE TITLE
SMTP Notification Channel Crash

### ISSUE THREAD

**Issue by sapiderman** [hyperjumptech/monika#763]
**Describe the bug**
When using SMPT as notification channel, Monika crashes

**To Reproduce**
1. Setup monika.yml to use `type: smtp` for notification

```yaml
notifications:
  - id: smtp-test
    type: smtp
    data:
      hostname: smtp.mailtrap.io
      port: 25
      username: sapiderman
      password: abcdefghijk
      recipients:
        - "sapiderman@hyperjump"
```

2. Run `monika -c monika.yml`

**Expected behavior**
Notification sent to smtp

**Desktop**
 - OS: WIndows 11 Home (version 22H2)
 - ~~OS: Mac Monterey 12.4 x86~~ => works on mac it turns out
 - Monika Version 1.9.1, 1.9.0, 1.8.1

Note: Runs fine on Pop!_OS 22_04 LTS

**Windows Screenshot**
![image](https://user-images.githubusercontent.com/964106/178191483-a0bcb053-2383-47c8-b1e2-40e0cf052c09.png)

**Mac Screenshot**
![image](https://user-images.githubusercontent.com/964106/178191229-e9d30995-fa1b-4233-afd7-fbf855b34dc7.png)

**Comment by ilmiawan** [comment]
dari screenshot di deskripsi, error nya karena indent nya kebanyakan untuk `type: smtp` harusnya sejajar dengan `id`. 
![Screen Shot 2022-07-19 at 14 36 21](https://user-images.githubusercontent.com/8952493/179694014-3cbfcb3e-8404-420e-ba3f-acd3f0481115.png)
di local gw error gara2 salah settingan smtp. timeout pas coba kirim email.

**Comment by nicnocquee** [comment]
I tried using the latest monika @hyperjumptech/monika/1.9.3 darwin-x64 node-v16.14.2 using the following notif config on macOS 12.4 (21F79).

```yaml
 - id: unique-id-smtp
    type: smtp
    data:
      recipients:
        - somegmail@gmail.com
      hostname: smtp.gmail.com
      port: 587
      username: mygmail@gmail.com
      password: mypassword
```
 
It doesn't crash.
