### ISSUE TITLE
Docs: Add information about time units in all examples

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#808]
Due to the difference of units used in `interval`, `timeout`,  and`response.time`, we should add the unit information in all of the examples. 

For example, in [Pass Response Data as Headers value](https://monika.hyperjump.tech/guides/examples#pass-response-data-as-headers-value) page, the example should have comments which explains the units being used.

```yaml
probes:
  - id: '1'
    name: Probing Github
    description: simulate html form submission
    interval: 10 # in seconds
    requests:
      - method: POST
        url: https://reqres.in/api/login
        timeout: 7000 # in milliseconds
        body:
          email: eve.holt@reqres.in
          password: cityslicka
      - method: POST
        url: https://reqres.in/api/users/
        timeout: 7000  # in milliseconds
        body:
          name: morpheus
          job: leader
        headers:
          Authorization: Bearer {{ responses.[0].body.token }}
    incidentThreshold: 3
    recoveryThreshold: 3
    alerts:
      - query: response.status > 299
        message: Target is not healthy. It has not been returning status code 2xx.
      - query: response.time > 2000  # in milliseconds
        message:
          Target is not healthy. The response time has been greater than 2000
          ms.
```
