### ISSUE TITLE
Create config or run Monika from a simple text file

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#828]
Now that Monika can create config or run from Postman, Insomnia, HAR, and sitemap, it'd be great if Monika can also create/run from a simple text file that contains the URL to probe on every line. For example, from the following text file

```
https://monika.hyperjump.tech
https://github.com
```

a configuration as the following will be generated:

```yaml
notifications:
  - id: desktop
    type: desktop
probes:
  - id: "probe-0"
    name: "Probe 0"
    incidentThreshold: 3
    recoveryThreshold: 3
    interval: 30
    alerts:
      - query: "response.status != 200"
        message: " Http Response status code is not 200!"
    requests:
      - method: GET
        url: "https://monika.hyperjump.tech/"
        timeout: 10000
  - id: "probe-1"
    name: "Probe 1"
    incidentThreshold: 3
    recoveryThreshold: 3
    interval: 30
    alerts:
      - query: "response.status != 200"
        message: " Http Response status code is not 200!"
    requests:
      - method: GET
        url: "https://github.com/"
        timeout: 10000
```
