### ISSUE TITLE
Monitor Redis

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#858]
As mentioned in [this discussion](https://github.com/hyperjumptech/monika/discussions/843), it'd be great if Monika can also check if a redis server is running. Maybe using ping command as mentioned in [this Stack Overflow](https://stackoverflow.com/a/64934377/401544).

Then user can define the configurations for connecting to redis in the `probes` property:

```yaml
probes:
  - id: 'check-redis'
    redis:
      host: '<hostname>'
      port: <port>
      password: '<password>'
```

Just like `tcp` and `ping` probing that we already have, user doesn't need to define any alerts for the `redis` checking.

So, todo:

- [x] Monitor Redis server, send notification when it cannot be reached after reaching threshold.
- [ ] Update [monika-config-schema.json](https://github.com/hyperjumptech/monika/blob/main/monika-config-schema.json) to include the new properties.
- [x] Add in the documentation.

**Comment by sapiderman** [comment]
Proposing using this format

```yaml
    redis:
      - host: 172.11.0.5
        port: 1234
```    
so something like this: when used
```yaml
probes:
  - id: 'redis-id'
    name: redis check
    description: check redis availability
    interval: 10 # in seconds
    redis:
      - host: 172.11.0.5
        port: 1234
    alerts: []
```
