### ISSUE TITLE
Monitor Postgres

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#859]
As mentioned in [this discussion](https://github.com/hyperjumptech/monika/discussions/843), it'd be great if Monika can also check if a postgres is running. Maybe using [this function](https://node-postgres.com/api/client#clientconnect):

```javascript
const { Client } = require('pg')
const client = new Client({
  host: 'my.database-server.com',
  port: 5334,
  user: 'database-user',
  password: 'secretpassword!!',
})
client.connect(err => {
  if (err) {
    console.error('connection error', err.stack)
  } else {
    console.log('connected')
  }
})
```

```yaml
probes:
  - id: 'check-redis'
    postgres:
      host: '<hostname>'
      port: <port>
      password: '<password>'
      user: <user>
```

Just like `tcp` and `ping` probing that we already have, user doesn't need to define any alerts for the `postgres` checking.

So, todo:

- [x] Monitor Postgres, send notification when it cannot be reached after reaching threshold.
- [x] Update [monika-config-schema.json](https://github.com/hyperjumptech/monika/blob/main/monika-config-schema.json) to include the new properties.
- [x] Add in the documentation.
