### ISSUE TITLE
Create docker image from any given version

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#889]
For testing purposes, we need a GitHub Actions workflow to create a docker image from any version, e.g., the nightly versions.

- [ ] Create a GitHub workflow that can be run manually and accept a version. This workflow then will create and publish a docker image of Monika of the given version.

Example:

```
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Monika NPM version to create docker image'
        required: true
        type: string
```
