### ISSUE TITLE
Integrate Sonar Cloud

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#901]
For the sake of improving and maintaining code quality, let's integrate Sonar Cloud in the pipeline.

```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

sonar-project.properties file:

```
sonar.projectKey=monika
sonar.organization=hyperjump

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=monika
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
```
