### ISSUE TITLE
Monitor MySQL Client

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#913]
It will be great if we can monitor MySQL instances. We can use `SELECT 1` or `SHOW STATUS` query to check if it is working.

The input would be something like this:

```
  - id: 'check-mysql'
    mysql:
      url: <mysql_connection_url> # required if the host, port, password, and user is empty
      host: '<hostname>' # required if url is empty
      port: <port> # required if url is empty
      password: '<password>' # required if url is empty
      user: <user> # required if url is empty
```

You may refer to [Redis Client probing.](https://github.com/hyperjumptech/monika/blob/main/src/components/redis-request/index.ts)
