### ISSUE TITLE
Monitor MongoDB Client

### ISSUE THREAD

**Issue by dennypradipta** [hyperjumptech/monika#914]
It will be great if we can monitor MongoDB clients.

We can use `db.stats().ok;` or `db.runCommand({ ping: 1 });` query to check if the `ok` value is equal to 1
![image](https://user-images.githubusercontent.com/16670475/194760119-ef54c274-98f2-4db9-89f3-f6ed8adca4f4.png)

The input would be something like this:

```
  - id: 'check-mongodb'
    mongodb:
      url: <mongodb_connection_url> # required if the host, port, password, and user is empty
      host: '<host>' # required if url is empty
      port: <port> # required if url is empty
      password: '<password>' # required if url is empty
      user: <user> # required if url is empty
```

You may refer to [Redis Client probing.](https://github.com/hyperjumptech/monika/blob/main/src/components/redis-request/index.ts)
