### ISSUE TITLE
Cannot run config generated from config generator

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#954]
**Describe the bug**
Monika crashed when running from a configuration file generated by config generator.

**To Reproduce**
1. Use the following configuration which was generated by config generator:

```yaml
notifications:
  - id: 3879020a-6b5c-4d9f-ac2a-e46d97549051
    type: desktop
probes:
  - id: a6138467-0e9e-45df-96b1-3ecf7e92463c
    name: Wikiexport Landing
    description: Landing page of wiki export
    interval: 10
    requests:
      - url: https://wikiexport.jp
        body: {}
        timeout: 10000
        headers:
          User-Agent: >-
            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
            (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        method: GET
    incidentThreshold: 5
    recoveryThreshold: 5
    alerts:
      - &ref_0
        query: response.status < 200 or response.status > 299
        message: Target is not healthy. It has not been returning status code 2xx.
  - id: 10919902-3f7b-4284-b4d2-887a2f0d5cb9
    name: Wikiexport Admin
    description: ''
    interval: 10
    requests:
      - url: https://admin.wikiexport.jp
        body: {}
        timeout: 10000
        headers:
          User-Agent: >-
            Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
            (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
        method: GET
    incidentThreshold: 5
    recoveryThreshold: 5
    alerts:
      - *ref_0

```

2. Run `monika -c <the above config path>`
3. Monika crashed with errors:

```
monika -c ~/Downloads/monika-wikiexport.yml

It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html
INFO: Monika is running from: Bern - Sunrise GmbH () - NMBPM1 ()
INFO: Updating config
/Users/nico/.nvm/versions/node/v18.12.1/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/errors/index.js:28
        err = new cli_2.CLIError(input, options);
              ^

CLIError: Errors detected in config file: /Users/nico/Downloads/monika-wikiexport.yml, please recheck
    at Object.error (/Users/nico/.nvm/versions/node/v18.12.1/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at Monika.error (/Users/nico/.nvm/versions/node/v18.12.1/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/command.js:103:23)
    at Monika.run (/Users/nico/.nvm/versions/node/v18.12.1/lib/node_modules/@hyperjumptech/monika/lib/index.js:197:18)
    at async Monika._run (/Users/nico/.nvm/versions/node/v18.12.1/lib/node_modules/@hyperjumptech/monika/node_modules/@oclif/core/lib/command.js:80:22) {
  oclif: { exit: 1 },
  code: undefined
}

Node.js v18.12.1
```

**Expected behavior**
Monika doesn't crash

**Desktop (please complete the following information):**
 - OS: macOS Monterey (12.6 (21G115))
 - Version @hyperjumptech/monika/1.14.0 darwin-arm64 node-v18.12.1

**Additional context**

Not sure if this is relevant, but VSCode shows config error:

<img width="647" alt="Screenshot 2022-12-08 at 09 40 37" src="https://user-images.githubusercontent.com/311343/206399424-d62b60e5-d3d7-4113-ab13-fd33a2b92d5d.png">
