### ISSUE TITLE
Matrix notification support

### ISSUE THREAD

**Issue by notramo** [hyperjumptech/monika#979]
Please add [Matrix](https://matrix.org) notification support. It is an open-source, E2EE chat protocol, which became quite popular in the FLOSS communities in the past few years. It has an official TypeScript SDK: https://github.com/matrix-org/matrix-js-sdk
If possible, please add E2EE support too.

**Comment by sapiderman** [comment]
thanks for the issue @notramo, we'll take a look at it.

**Comment by Fijxu** [comment]
+1 in this, i use matrix in a daily basis and it would be very useful to have matrix support since i don't use whatsapp and other well known services

**Comment by dennypradipta** [comment]
Hi, @Fijxu @notramo I am considering working on the Monika integration with Matrix. I will experiment a bit on this and let you both know if it's ready.

For accelerating development, I need to ask something regarding Matrix: So basically you only need the Room ID and the Access Token for the integration right? Have you both experienced connecting Matrix with something else?

**Comment by Fijxu** [comment]
> For accelerating development, I need to ask something regarding Matrix: So basically you only need the Room ID and the Access Token for the integration right? Have you both experienced connecting Matrix with something else?

I don't really know, but i know for bots or integrations like this it should be an appservice (since it will not be a normal user and it eliminates the process of doing manual logins) that it connects to the matrix instance.


It is also needed to generate a `registration.yaml` (that file is generally generated by the program, in this case monika) and stick it into the matrix server config (There is more than one server implementation of matrix, Like Synapse, Dendrite, Conduit, but the `registration.yaml` file it's universal as far as i know and it should work in all implementations)

Here is an example how a `registration.yaml` looks like:
```yaml
id: discord
// This is where the app service will listen to
url: http://127.0.0.1:3131
as_token: [REDACTED]
hs_token: [REDACTED]
sender_localpart: [REDACTED]
rate_limited: false
namespaces:
    users:
        - regex: ^@discordbot:zzls\.xyz$
          exclusive: true
        - regex: ^@discord_.*:zzls\.xyz$
          exclusive: true
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
```

https://spec.matrix.org/latest/#application-service-api

That is all i known about matrix, i don't know if is there other way to do it. Thanks for your time
