### ISSUE TITLE
Loading multiple config files does not work

### ISSUE THREAD

**Issue by luizrojo** [hyperjumptech/monika#983]
**Describe the bug**
When providing multiple configuration files as described on the documentation, only the last file is loaded.

**To Reproduce**
1. Create a file for the probes
```
probes:
  - id: 'github'
    name: GitHub
    description: Multiple GitHub probes
    requests:
      - url: https://github.com
        timeout: 7000
      - url: https://github.com/hyperjump
        timeout: 7000
```
2. Create a file for the notifications
```
notifications:
  - id: desktop
    type: desktop
```
3. Run monika passing both files as parameters
`./monika -c probes.yml notifications.yml`
4. Get an error message
```
INFO: Monika is running from: Amsterdam - XXXXXXX - XXXXX (xx.xx.xx.xx)
INFO: Updating config
ERROR: Probes object does not exists or has length lower than 1!
```

**Expected behavior**
Both files should be loaded, giving the possibility to split configurations
(This also does not work with remote URL configs)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Ventura 13.1
